#!/bin/bash

#If a kernel update occurs through rchroot or rupdate, RAM Session's
#grub entry will immediately be modified to use the new kernel. If a
#squashfs image with the updated modules is not created immediately
#(at least before a reboot), the RAM Session will be forced to use a
#kernel it has no modules for. This creates a file called /WARN in the
#RAM Session that rchroot and rupdate can detect, and warn people to
#recreate the squashfs image, or force them to do it

if [[ -e /RAM_Session ]]
then
	sudo touch /WARN
fi
